apiVersion: v1
kind: Service
metadata:
  name: saturno-service-back
spec:
  type: NodePort
  selector:
    role: saturno-api
  ports:
  - port: 3050
    targetPort: 3000
    protocol: TCP
    nodePort: 31000